# Generated by Django 4.2 on 2023-04-03 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drag_n_drop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changes',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='changes',
            name='new_item',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='drag_n_drop.todo'),
        ),
    ]
