# Generated by Django 4.2 on 2023-04-03 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drag_n_drop', '0002_rename_user_id_changes_user_alter_changes_new_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='user_id',
            new_name='user',
        ),
    ]
