version: '3.8'

services:
  db:
      restart: always
      image: postgres:13
      container_name: todos-db
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASS=secret
        - POSTGRES_PORT=5432
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data/
  
volumes:
  postgres_data: