# Generated by Django 4.2 on 2023-04-09 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos_api', '0003_alter_todo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-order', '-created_at']},
        ),
    ]
