# Generated by Django 4.2 on 2023-04-22 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos_api', '0004_alter_todo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-created_at']},
        ),
    ]
